/**
 *  @file      main.js
 *  @brief     Principal file
 *  @author    Created by Miakel Juillet
 *  @version   23.05.2023
 */

import { horizonAPIFilter } from './src/model/dataFilter.js';
import { GetAsteroid } from './src/controller/requests.js'
import { Renderer } from './src/model/classes/Renderer.js';
import { Planet } from './src/model/classes/Planet.js';
import { Asteroid } from './src/model/classes/Asteroid.js';

/** 
* Main function of teh project will be ussed first
*/
async function main() {

  const allPlanets = await import('./src/assets/AllPlanetsData-08-05-2023.json');
  let planetList = [];

  // Loop around all planets getted from the allPlanets data
  allPlanets.planets.forEach( element => {
    const filteredPlanet = horizonAPIFilter(element);
    const planet = generatePlanets(filteredPlanet);
    planetList.push(planet);
  });

  const renderer = new Renderer(document.getElementById('canvas'), planetList);

  const animate = () => {
    requestAnimationFrame(animate);
    renderer.animate();
  };
  animate();


  generateAsteroid()
}

/** 
* Generates planets with the planet class by using planet filtred 
* @param  filteredPlanet - Data from the planet that's filtred in amont
* @return planet object generated by the class
*/
function generatePlanets(filteredPlanet){
  const planet = new Planet(
    filteredPlanet.id,
    filteredPlanet.name,
    filteredPlanet.sizeRadius,
    filteredPlanet.name + ".jpg",
    filteredPlanet.coordinate,
    filteredPlanet.rotationSpeed,
    filteredPlanet.rotationDuration,
    filteredPlanet.orbitSpeed,
    filteredPlanet.orbitDuration,
    filteredPlanet.meanTemperature
  )
  return planet;
}

async function generateAsteroid(){
  const gettedObjects = await GetAsteroid();
  console.log(gettedObjects);
  gettedObjects.forEach(element => {
    const asteroid = new Asteroid(
      element.id,
      element.name,
      element.estimated_diameter.kilometers.estimated_diameter_max,
      element.close_approach_data[0].close_approach_date_full,
      element.is_potentially_hazardous_asteroid,
      element.close_approach_data[0].orbiting_body,
      element.close_approach_data[0].miss_distance.kilometers
    )
    console.log(asteroid)
  });
}


main();